In [1]:
# Lab01
# Revisão básica e rápida sobre o uso do sobre o Numpy e Pandas

In [2]:
import numpy as np

In [3]:
lista_numeros = [1,2,3,4,5,6,7,8,9,10,11,12]
np.mean(lista_numeros)

np.float64(6.5)

In [4]:
lista_numeros = [1,2,3,4,5,6,7,8,9,10,11,12]
array_numeros = np.array(lista_numeros)
array_numeros.mean()

np.float64(6.5)

In [5]:
type(lista_numeros)

list

In [6]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
np.arange(3, 25)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [8]:
np.arange(-7.1,7)

array([-7.1, -6.1, -5.1, -4.1, -3.1, -2.1, -1.1, -0.1,  0.9,  1.9,  2.9,
        3.9,  4.9,  5.9,  6.9])

In [9]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])